name: Develop Branch Workflow

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      ref: ${{ github.event.pull_request.head.sha || github.sha }}

  test:
    needs: lint
    uses: ./.github/workflows/test.yml
    with:
      ref: ${{ github.event.pull_request.head.sha || github.sha }}
