name: Release Branch Workflow

on:
  push:
    branches:
      - '*.x'
  pull_request:
    branches-ignore:
      - '*.x' # ignore refs/heads/N.x

permissions:
  contents: write
  pull-requests: write
  issues: write
  packages: write

jobs:
  verify:
    if: github.event_name == 'push'
    uses: ./.github/workflows/verify.yml

  lint:
    uses: ./.github/workflows/lint.yml
    with:
      ref: ${{ github.sha }}

  test:
    needs: lint
    uses: ./.github/workflows/test.yml
    with:
      ref: ${{ github.sha }}

  release:
    if: |
      github.event_name == 'push' &&
      success() &&
      needs.verify.outputs.is_valid == 'true'
    needs: [verify, test]
    uses: ./.github/workflows/release.yml
